@startuml

package #FFFF99 {
    title DesktopApp

    package Dependencies #FFFF99
    package Config #FFFF99
    package Constants #FFFF99
    package Helpers #FFFF99
    package Interops #FFFF99
    package Models #FFFF99
    package Resources #FFFF99
    package Security #FFFF99
    package Services #FFFF99
    package ViewModels #FFFF99

    ' Relationships (chỉ dùng <<import>> và <<access>>)
    Config ..> Constants : <<import>>
    Services ..> Models : <<import>>
    Services ..> Helpers : <<access>>
    Services ..> Interops : <<import>>
    Services ..> Security : <<access>>
    ViewModels ..> Models : <<import>>
    ViewModels ..> Services : <<access>>
    Helpers ..> Constants : <<import>>
    Security ..> Helpers : <<access>>
    Dependencies ..> Services : <<import>>
    Resources ..> Models : <<import>>
}

@enduml 